#!/system/bin/sh
# Install modules only for first boot
mdpath=/system/lib;
m=`find $mdpath -type f -name *.ko`;
mdinstall=/system/lib/modules;
if [ $m != "" ];
then
    # Install modules before modprobe
    for installm in $mdinstall/cfq_iosched.ko $mdinstall/cpufreq_conservative.ko $mdinstall/cpufreq_performance.ko $mdinstall/cpufreq_powersave.ko $mdinstall/cpufreq_userspace.ko $mdinstall/deadline_iosched.ko $mdinstall/mmc_block_test.ko $mdinstall/scsi_wait_scan.ko $mdinstall/test_iosched.ko;
    do
        insmod $installm;
    done;
fi;
